package:
  name: porebuilder
  version: "0.0.0"

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - mbuild
    - mdtraj
    - parmed
    - openbabel

test:
  requires:
    - pytest
  imports:
    - porebuilder

about:
  home: https://github.com/rmatsum836/Pore-Builder
  license: MIT License
  summary: mBuild Recipe to build carbon slitpores
