name: Build and push Docker images
on:
    push:
        branches: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Setup Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        -
          name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2.2.0
          with:
              builder: ${{ steps.buildx.outputs.name }}
              context: ./docker
              file: ./docker/Dockerfile
              push: true
              tags: rmatsum/pyfooty:latest
        -
          name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
